### PR TITLE
Allow subsetting with Vector of labels

### PR DESCRIPTION
**Pull request by bgctw**
deals with #54

### CODE REVIEW

**Comment by bgctw** [comment]
I do not understand what the error on broadcasting has to do with the introduced changes. Anyway, the Rosenbrock23 solver computes `x .* x'`  where x is an LArray.
Hence, we need a broadcasting rule that tells the type of the 2D Array for storing the broadcasting results.

Currently, only the 1D case is handled:
```
struct LAStyle{T,N,L} <: Broadcast.AbstractArrayStyle{N} end
LAStyle{T,N,L}(x::Val{1}) where {T,N,L} = LAStyle{T,N,L}()
```

I added the following two lines to larray.jl
```
# same dimension -> keep Labels
LAStyle{T,N,L}(x::Val{N}) where {T,N,L} = LAStyle{T,N,L}()
# different dimension -> convert to plain array
LAStyle{T,N,L}(x::Val{M}) where {T,N,L,M} = Base.Broadcast.DefaultArrayStyle{M}()
```

Is this a viable semantics?

**Comment by ChrisRackauckas** [comment]
Don't worry about the broadcasting. I fixed it via https://github.com/JuliaDiffEq/LabelledArrays.jl/commit/762d0a48b5ab855024287a6d15e7e66a2cbef298

**Comment by ChrisRackauckas** [comment]
I can take it from here.

**Comment by bgctw** [comment]
On Travis, now basic tests fail, such as:
`x .+ 1 isa LArray`
But I cannot reproduce these failures at my local checkout.

**Comment by ChrisRackauckas** [comment]
Supersceded by https://github.com/JuliaDiffEq/LabelledArrays.jl/pull/56

**Pull request closed without merging**
